ALTER TABLE `products`
  ADD COLUMN `ncm` VARCHAR(8) NULL,
  ADD COLUMN `cest` VARCHAR(7) NULL,
  ADD COLUMN `cfop` VARCHAR(4) NULL DEFAULT '5102',
  ADD COLUMN `origem` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `unidade_comercial` VARCHAR(191) NOT NULL DEFAULT 'UN',
  ADD COLUMN `unidade_tributavel` VARCHAR(191) NOT NULL DEFAULT 'UN',
  ADD COLUMN `csosn` VARCHAR(191) NULL DEFAULT '102',
  ADD COLUMN `cst_icms` VARCHAR(191) NULL,
  ADD COLUMN `icms_aliquota` DECIMAL(5, 2) NULL,
  ADD COLUMN `pis_cst` VARCHAR(191) NULL,
  ADD COLUMN `pis_aliquota` DECIMAL(5, 2) NULL,
  ADD COLUMN `cofins_cst` VARCHAR(191) NULL,
  ADD COLUMN `cofins_aliquota` DECIMAL(5, 2) NULL;
