import { Link, useParams } from "react-router-dom";
import { ArrowRight, CakeSlice, Gift, Heart, ShoppingBag, Sparkles } from "lucide-react";
import StoreSEO from "../../../../components/store/StoreSEO";
import { useStore } from "../../StoreLayout";
import { buildStorePath, productRouteSegment, resolveStoreSlug } from "../../store-routing";

const imageOf = (product: { image_url?: string | null; images?: unknown }) =>
  (Array.isArray(product.images) && typeof product.images[0] === "string" ? product.images[0] : product.image_url) || null;
const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export default function StoreFront() {
  const { slug: routeSlug } = useParams();
  const { tenant, products, categories, addToCart } = useStore();
  const slug = resolveStoreSlug(routeSlug);
  const storePath = (suffix = "") => buildStorePath(slug, suffix);
  const active = products.filter((product) => product.is_active);
  const featured = (active.filter((product) => product.is_featured).length ? active.filter((product) => product.is_featured) : active).slice(0, 8);
  const heroImages = featured.map(imageOf).filter(Boolean) as string[];
  const isMadeToOrder = tenant.policies?.storefront?.checkout_mode === "order_request";
  const tagline = tenant.hero_tagline || "Doces caseiros preparados com carinho para deixar qualquer momento mais especial.";

  return <main className="min-h-screen overflow-hidden bg-[#fff8fb] text-[#3d2431]">
    <StoreSEO title={`${tenant.name} | Doces e encomendas`} description={tenant.about_text || `${tenant.name}: doces caseiros e encomendas feitos com carinho.`} image={tenant.banner_url || tenant.logo_url} url={typeof window !== "undefined" ? window.location.href : ""} siteName={tenant.name} keywords={`${tenant.name}, doceria, doces caseiros, encomendas, Tatuí`} />

    <section className="border-b border-pink-100 bg-[radial-gradient(circle_at_12%_16%,#fecdd3_0,transparent_24%),radial-gradient(circle_at_84%_18%,#fde68a_0,transparent_18%),linear-gradient(135deg,#fff1f6_0%,#fffaf7_52%,#fdf2f8_100%)]">
      <div className="mx-auto grid max-w-[1440px] items-center gap-8 px-5 py-10 md:px-8 lg:grid-cols-[1.05fr_.95fr] lg:py-14">
        <div className="max-w-xl">
          <span className="inline-flex items-center gap-2 rounded-full border border-pink-200 bg-white/80 px-4 py-2 text-[10px] font-extrabold uppercase tracking-[.18em] text-pink-700"><Sparkles size={13} /> Doces feitos para celebrar</span>
          <h1 className="mt-5 font-[Cormorant_Garamond] text-5xl font-bold leading-[.88] tracking-[-.05em] text-[#4a2135] sm:text-6xl lg:text-7xl">Um carinho<br /><em className="font-normal text-pink-600">em cada doce.</em></h1>
          <p className="mt-5 max-w-md text-base leading-relaxed text-[#765361]">{tagline}</p>
          <div className="mt-7 flex flex-wrap gap-3"><Link to={storePath("/catalogo")} className="inline-flex h-11 items-center gap-2 rounded-full bg-pink-600 px-5 text-[11px] font-extrabold uppercase tracking-[.13em] text-white shadow-[0_14px_28px_rgba(219,39,119,.23)] transition hover:-translate-y-0.5 hover:bg-pink-700"><ShoppingBag size={15} /> Ver delícias <ArrowRight size={14} /></Link><a href="#colecao" className="inline-flex h-11 items-center gap-2 rounded-full border border-pink-200 bg-white/80 px-5 text-[11px] font-extrabold uppercase tracking-[.13em] text-pink-700 transition hover:bg-white"><Gift size={15} /> Para presentear</a></div>
          <div className="mt-8 flex flex-wrap gap-x-7 gap-y-2 text-[11px] font-bold text-[#805d6c]"><span className="inline-flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-pink-500" /> Produção sob encomenda</span><span className="inline-flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-amber-400" /> Atendimento personalizado</span></div>
        </div>
        <div className="relative mx-auto h-[300px] w-full max-w-[460px] sm:h-[350px]">{heroImages.length ? <><div className="absolute left-[5%] top-[8%] grid h-[64%] w-[45%] place-items-center overflow-hidden rounded-[3rem_3rem_1.5rem_1.5rem] border-[8px] border-white bg-white/75 shadow-[0_18px_38px_rgba(93,42,63,.15)]"><img src={heroImages[0]} alt="Doce em destaque" className="h-full w-full object-contain p-2" /></div><div className="absolute bottom-[1%] right-[3%] grid h-[72%] w-[52%] place-items-center overflow-hidden rounded-[1.5rem_1.5rem_3rem_1.5rem] border-[8px] border-white bg-white/75 shadow-[0_18px_38px_rgba(93,42,63,.15)]"><img src={heroImages[1] || heroImages[0]} alt="Encomenda em destaque" className="h-full w-full object-contain p-2" /></div><div className="absolute left-[35%] top-[2%] grid h-16 w-16 place-items-center rounded-full bg-[#4a2135] text-center text-[8px] font-black uppercase tracking-wider text-white shadow-xl">feito<br />com amor</div></> : <div className="grid h-full place-items-center rounded-[3rem] border border-pink-200 bg-white/60 text-center"><CakeSlice size={52} className="text-pink-300" /><p className="mt-3 max-w-48 text-sm font-bold text-pink-800">Adicione fotos dos seus doces para completar sua vitrine.</p></div>}</div>
      </div>
    </section>

    <section id="colecao" className="mx-auto max-w-[1440px] px-5 py-12 md:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-pink-600">Escolha o seu momento</p><h2 className="mt-2 font-[Cormorant_Garamond] text-4xl font-bold tracking-[-.04em] text-[#4a2135] sm:text-5xl">Delícias para compartilhar.</h2></div><Link to={storePath("/catalogo")} className="hidden items-center gap-1 text-[11px] font-extrabold uppercase tracking-wider text-pink-700 sm:inline-flex">Ver catálogo <ArrowRight size={14} /></Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.slice(0, 4).map((category, index) => <Link key={category.id} to={storePath(`/catalogo?cat=${category.id}`)} className="group relative min-h-40 overflow-hidden rounded-2xl bg-[#fdf0f5] p-5 transition hover:-translate-y-1 hover:shadow-xl"><div className="absolute inset-0">{category.cover_url ? <img src={category.cover_url} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <div className={`h-full w-full ${index % 2 ? "bg-[#fff0dd]" : "bg-[#fce7f3]"}`} />}</div><div className="absolute inset-0 bg-gradient-to-t from-[#3d2431]/75 via-[#3d2431]/10 to-transparent" /><div className="absolute bottom-5 left-5 right-5 text-white"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] opacity-75">Coleção {String(index + 1).padStart(2, "0")}</p><p className="mt-1 text-lg font-bold">{category.name}</p><span className="mt-2 inline-flex items-center gap-1 text-[10px] font-extrabold uppercase tracking-wider">Ver opções <ArrowRight size={12} /></span></div></Link>)}</div></section>

    <section className="bg-[#4a2135] py-12 text-white"><div className="mx-auto max-w-[1440px] px-5 md:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-pink-300">Mais pedidos</p><h2 className="mt-2 font-[Cormorant_Garamond] text-4xl font-bold tracking-[-.04em] sm:text-5xl">Favoritos da casa.</h2></div><Link to={storePath("/catalogo")} className="inline-flex items-center gap-2 text-[11px] font-extrabold uppercase tracking-wider text-pink-200">Ver todos <ArrowRight size={14} /></Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{featured.map((product) => <article key={product.id} className="rounded-2xl bg-white p-3 text-[#3d2431]"><Link to={storePath(`/produto/${productRouteSegment(product)}`)} className="grid h-52 place-items-center rounded-xl bg-[#fff6f8] p-3 sm:h-56">{imageOf(product) ? <img src={imageOf(product)!} alt={product.name} className="h-full w-full object-contain" /> : <CakeSlice size={38} className="text-pink-200" />}</Link><div className="px-1 pt-3"><p className="text-[9px] font-extrabold uppercase tracking-[.16em] text-pink-500">{product.category_name || "Doceria"}</p><div className="mt-1 flex items-start justify-between gap-3"><Link to={storePath(`/produto/${productRouteSegment(product)}`)} className="text-[15px] font-extrabold leading-snug">{product.name}</Link><Heart size={16} className="shrink-0 text-pink-300" /></div><div className="mt-3 flex items-center justify-between"><p className="text-[10px] font-extrabold uppercase tracking-wide text-pink-700">{isMadeToOrder ? "Sob encomenda" : money(Number(product.discount_price || product.price))}</p><button onClick={() => addToCart(product)} className="rounded-full bg-pink-600 px-3 py-2 text-[9px] font-extrabold uppercase tracking-wider text-white transition hover:bg-pink-700">Adicionar</button></div></div></article>)}</div></div></section>
  </main>;
}
