import { Link, useParams } from "react-router-dom";
import { ArrowRight, CakeSlice, Heart, ShoppingBag } from "lucide-react";
import StoreSEO from "../../../../components/store/StoreSEO";
import { useStore } from "../../StoreLayout";
import { buildStorePath, productRouteSegment, resolveStoreSlug } from "../../store-routing";

const imageOf = (product: { image_url?: string | null; images?: unknown }) =>
  (Array.isArray(product.images) && typeof product.images[0] === "string" ? product.images[0] : product.image_url) || null;
const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export default function StoreFront() {
  const { slug: routeSlug } = useParams();
  const { tenant, products, categories, addToCart } = useStore();
  const slug = resolveStoreSlug(routeSlug);
  const path = (suffix = "") => buildStorePath(slug, suffix);
  const active = products.filter((product) => product.is_active);
  const featured = (active.filter((product) => product.is_featured).length ? active.filter((product) => product.is_featured) : active).slice(0, 8);
  const heroProducts = featured.filter((product) => imageOf(product)).slice(0, 2);
  const isMadeToOrder = tenant.policies?.storefront?.checkout_mode === "order_request";

  return <main className="min-h-screen bg-[#f7f6ed] text-[#59451f]">
    <StoreSEO title={`${tenant.name} | Doces caseiros`} description={tenant.about_text || `${tenant.name}: doces caseiros feitos com carinho.`} image={tenant.banner_url || tenant.logo_url} url={typeof window !== "undefined" ? window.location.href : ""} siteName={tenant.name} keywords={`${tenant.name}, doces caseiros, encomendas, Tatuí`} />

    <section className="border-b border-[#e5d9c1] bg-[#f7f6ed]">
      <div className="bg-[#bd3437] text-[#fff7e6]"><div className="mx-auto flex max-w-[1280px] items-center gap-6 px-5 py-4 md:px-8"><p className="text-[11px] font-bold uppercase tracking-[.35em]">Moça Reis Doces Caseiros</p><span className="h-px flex-1 bg-[#f2dfaa]/80" /></div></div>
      <div className="mx-auto grid max-w-[1280px] items-center gap-10 px-5 py-12 md:px-8 lg:grid-cols-[.9fr_1.1fr]">
        <div className="max-w-xl"><p className="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#bd3437]">Tradicional de Tatuí</p><h1 className="mt-3 text-4xl font-extrabold leading-[1.04] tracking-[-.05em] text-[#70541c] sm:text-5xl">O melhor do<br />doce caseiro.</h1><p className="mt-5 max-w-md text-[15px] leading-relaxed text-[#765e33]">Produtos artesanais feitos com ingredientes selecionados, produção própria e aquele gostinho que acompanha gerações.</p><div className="mt-7 flex flex-wrap gap-3"><Link to={path("/catalogo")} className="inline-flex h-11 items-center gap-2 rounded-md bg-[#bd3437] px-5 text-[10px] font-extrabold uppercase tracking-[.14em] text-white transition hover:bg-[#9f292d]"><ShoppingBag size={15} /> Ver catálogo <ArrowRight size={14} /></Link><a href="#destaques" className="inline-flex h-11 items-center gap-2 rounded-md border border-[#bd3437] bg-transparent px-5 text-[10px] font-extrabold uppercase tracking-[.14em] text-[#bd3437] transition hover:bg-white">Produtos em destaque</a></div><p className="mt-7 text-[11px] font-semibold text-[#765e33]"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#bd3437]" /> Pedidos por encomenda · Atendimento personalizado</p></div>
        <div className="grid grid-cols-2 gap-4 border border-[#e5d9c1] bg-white p-4 shadow-[0_18px_45px_rgba(94,69,31,.08)]">{heroProducts.length ? heroProducts.map((product) => <div key={product.id} className="grid h-72 place-items-center bg-[#f7f6ed] p-3 sm:h-80"><img src={imageOf(product)!} alt={product.name} className="h-auto max-h-full w-auto max-w-full object-contain" /></div>) : <div className="col-span-2 grid h-72 place-items-center bg-[#f7f6ed] text-center text-[#bd3437]"><CakeSlice size={42} /><p className="mt-3 text-sm font-bold">Adicione as fotos dos produtos para completar a vitrine.</p></div>}</div>
      </div>
    </section>

    <section className="mx-auto max-w-[1280px] px-5 py-12 md:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#bd3437]">Catálogo de produtos</p><h2 className="mt-2 text-3xl font-extrabold tracking-[-.04em] text-[#70541c] sm:text-4xl">Encontre o seu doce favorito.</h2></div><Link to={path("/catalogo")} className="hidden items-center gap-1 text-[10px] font-extrabold uppercase tracking-wider text-[#bd3437] sm:inline-flex">Ver catálogo <ArrowRight size={14} /></Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.slice(0, 4).map((category) => { const sample = active.find((product) => product.category_id === category.id); const image = sample ? imageOf(sample) : null; return <Link key={category.id} to={path(`/catalogo?cat=${category.id}`)} className="group border border-[#e5d9c1] bg-white p-3 transition hover:border-[#bd3437]"><div className="grid h-40 place-items-center bg-[#f7f6ed] p-3">{image ? <img src={image} alt={category.name} className="h-auto max-h-full w-auto max-w-full object-contain transition group-hover:scale-[1.03]" /> : <CakeSlice size={32} className="text-[#d9bd7d]" />}</div><div className="px-1 pb-1 pt-4"><p className="text-[9px] font-extrabold uppercase tracking-[.18em] text-[#bd3437]">Linha de produtos</p><p className="mt-1 text-[15px] font-extrabold leading-snug text-[#70541c]">{category.name}</p><span className="mt-3 inline-flex items-center gap-1 text-[10px] font-extrabold uppercase tracking-wider text-[#bd3437]">Ver opções <ArrowRight size={12} /></span></div></Link>; })}</div></section>

    <section id="destaques" className="border-y border-[#e5d9c1] bg-white"><div className="mx-auto max-w-[1280px] px-5 py-12 md:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#bd3437]">Mais pedidos</p><h2 className="mt-2 text-3xl font-extrabold tracking-[-.04em] text-[#70541c] sm:text-4xl">Produtos em destaque.</h2></div><Link to={path("/catalogo")} className="hidden items-center gap-1 text-[10px] font-extrabold uppercase tracking-wider text-[#bd3437] sm:inline-flex">Ver todos <ArrowRight size={14} /></Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{featured.map((product) => <article key={product.id} className="border border-[#e5d9c1] bg-[#fffef9] p-3"><Link to={path(`/produto/${productRouteSegment(product)}`)} className="grid h-52 place-items-center bg-[#f7f6ed] p-3">{imageOf(product) ? <img src={imageOf(product)!} alt={product.name} className="h-auto max-h-full w-auto max-w-full object-contain" /> : <CakeSlice size={36} className="text-[#d9bd7d]" />}</Link><div className="px-1 pb-1 pt-3"><p className="text-[9px] font-extrabold uppercase tracking-[.16em] text-[#bd3437]">{product.category_name || "Doceria"}</p><div className="mt-1 flex items-start justify-between gap-2"><Link to={path(`/produto/${productRouteSegment(product)}`)} className="text-[15px] font-extrabold leading-snug text-[#70541c]">{product.name}</Link><Heart size={16} className="shrink-0 text-[#bd3437]" /></div><div className="mt-3 flex items-center justify-between gap-2"><span className="text-[10px] font-extrabold uppercase tracking-wide text-[#bd3437]">{isMadeToOrder ? "Sob encomenda" : money(Number(product.discount_price || product.price))}</span><button onClick={() => addToCart(product)} className="rounded-md bg-[#bd3437] px-3 py-2 text-[9px] font-extrabold uppercase tracking-wider text-white transition hover:bg-[#9f292d]">Adicionar</button></div></div></article>)}</div></div></section>
  </main>;
}
